version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'terraform-provider-spaceliftoutput_v{{ .Version }}'  # Fix binary naming

archives:
  - format: zip  # Ensure ZIP for all OS
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: 'terraform-provider-spaceliftoutput_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE*
      - README.md
    wrap_in_directory: false  # Ensure no extra folder inside ZIP

checksum:
  name_template: 'terraform-provider-spaceliftoutput_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
